#!/usr/bin/env bash

set -eu -o pipefail
pushd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" > /dev/null

pushd lifeweb > /dev/null
./update
popd > /dev/null

git pull
npm install
npx tsc -b
./build

popd > /dev/null
